### PR TITLE
return difference image and psf

### PR DESCRIPTION
**Pull request by burke86**

### CODE REVIEW

**Comment by burke86** [comment]
@griffin-h Simple PR implementing suggestions from my previous PR #3. Happy to iterate on your suggestions. Thanks for your work! I've implemented this into our TESS AGN pipeline. P.S. Do you have Zenodo or similar citation?

**Comment by burke86** [comment]
Ah, I see the Zenodo link in the readme now!

**Comment by griffin-h** [comment]
I think it's least confusing if we have the default be `output=None`, and just have it save to disk if someone provides a (non-empty) filename. What do you think?

**Comment by griffin-h** [comment]
For posterity: this is a continuation of the conversation in PR #3

**Comment by burke86** [comment]
Sounds reasonable to me!

**Comment by griffin-h** [comment]
Thanks for your help @burke86!

**Pull request merged**
